#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

cmdCommands() {
  declare SCRIPT_NAME
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  find "${TEXENV_LIBEXEC}" -maxdepth 1 -type f -name "texenv-*" |
    awk -F/ '{gsub("texenv-","");if($NF !~ /^-.*$/){print $NF}}' |
    grep -v "libs" |
    sort
}

cmdCommands "${@}"
