#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

helpCommands() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}            ")List available commands"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpEnv() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}                 ")Display ${SCRIPT_NAME%%-*} environment information"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpExec() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} <cmd> [args]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}             ")Execute command in current TeX Live version"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpFreeze() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}              ")Freeze installed TeX packages to requirements file"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -l, --lock  Freeze to lock file with TeX Live version"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpGlobal() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options] <version>"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}    ")Set global TeX Live version"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpInit() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}                ")Initialize ${SCRIPT_NAME%%-*} environment"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -           Output shell commands to set up ${SCRIPT_NAME%%-*} environment"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpInstall() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  case "${1:-}" in
    -l | --list)
      builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_NAME,,} [-l|--list] [options]"
      builtin echo "List available TeX Live versions"
      builtin echo "Options:"
      builtin echo "  -a, --all   List all available versions"
      builtin echo "  -h, --help  Show this help message"
      ;;
    *)
      SUBCMD_USAGE="${SUBCMD_NAME,,} [options] <version>"
      [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
      builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}   ")Install specified TeX Live version"
      [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
      [[ "${1:-}" != "desc" ]] && builtin echo "  -l, --list  List available versions"
      [[ "${1:-}" != "desc" ]] && builtin echo "  -f, --force Force reinstall if version is already installed"
      [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
      ;;
  esac
}

helpLocal() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options] <version>"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}     ")Set local TeX Live version"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpRehash() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}              ")Rebuild shims for installed TeX Live versions"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -f, --force  Force rebuild"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help   Show this help message"
}

helpRepo() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options] [<repo>]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}       ")Manage tlmgr repository"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -s, --show           Show current tlmgr repository"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -m, --mirror <repo>  Set tlmgr repository to specified mirror"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -r, --reset          Reset tlmgr repository to default"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help           Show this help message"
}

helpRestore() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}             ")Restore TeX packages from requirements file"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpRoot() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}                ")Show ${SCRIPT_NAME%%-*} root directory"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpShell() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options] <version>"
  [[ "${1:-}" != "desc" ]] && builtin echo "builtin echo 'Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}'"
  builtin echo "builtin echo '$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}     ")Spawn a new shell with specified TeX Live version'"
  [[ "${1:-}" != "desc" ]] && builtin echo "builtin echo 'If no version is specified, the currently configured shell-specific version is used'"
  [[ "${1:-}" != "desc" ]] && builtin echo "builtin echo 'Options:'"
  [[ "${1:-}" != "desc" ]] && builtin echo "builtin echo '  -h, --help  Show this help message'"
}

helpShims() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}               ")Show executable file(s) from ${SCRIPT_NAME%%-*} shims directory"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpUninstall() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options] <version>"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE} ")Uninstall specified TeX Live version"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpVersion() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}             ")Show current TeX Live version"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpVersions() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} [options]"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}            ")List installed TeX Live versions"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpWhence() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} <cmd>"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}                  ")Show path to command in all installed TeX Live versions"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpWhere() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} <cmd>"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}                   ")Show path to command in current TeX Live version"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

helpWhich() {
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  declare SUBCMD_USAGE
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${FUNCNAME[0]##help}"
  SUBCMD_USAGE="${SUBCMD_NAME,,} <cmd>"
  [[ "${1:-}" != "desc" ]] && builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SUBCMD_USAGE}"
  builtin echo "$([[ "${1:-}" == "desc" ]] && builtin echo "${SUBCMD_USAGE}                   ")Show path to shim for specified command"
  [[ "${1:-}" != "desc" ]] && builtin echo "Options:"
  [[ "${1:-}" != "desc" ]] && builtin echo "  -h, --help  Show this help message"
}

cmdHelp() {
  declare SCRIPT_NAME
  SCRIPT_NAME="${0##*/}"
  builtin echo "USAGE: ${SCRIPT_NAME%%-*} <command> [<args>]"
  builtin echo "Commands:"
  while read -r FUNC_NAME; do
    if [[ "${FUNC_NAME}" == "helpShell" ]]; then
      builtin echo "  $(builtin eval "$("${FUNC_NAME}" desc)")"
    else
      builtin echo "  $("${FUNC_NAME}" desc)"
    fi
  done <<< "${@}"
  builtin echo "  help                          Show this help message"
}

main() {
  declare HELP_FUNCS
  declare SUBCMD_NAMES
  declare PATTERNS
  HELP_FUNCS="$(declare -F | awk '/ help[A-Z][a-z]*$/{print $3}')"
  IFS=" " read -r -a SUBCMD_NAMES <<< "$(awk -v 'ORS= ' '{sub("help","");print tolower($0)}' <<< "${HELP_FUNCS}")"
  PATTERNS="$(
    IFS="|"
    builtin echo "${SUBCMD_NAMES[*]}"
  )"
  if [[ "${1:-}" != @(${PATTERNS}) ]]; then
    cmdHelp "${HELP_FUNCS}"
  else
    if [[ "${1:-}" == "install" ]]; then
      "help${1^}" "${@:2}"
    elif [[ "${1:-}" == "shell" ]]; then
      builtin eval "$("help${1^}")"
    else
      "help${1^}"
    fi
  fi
}

main "${@}"
