#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

cmdCommands() {
  declare SCRIPT_NAME
  SCRIPT_NAME="${0##*/}"
  case "${1:-}" in
    -h | --help)
      builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SCRIPT_NAME##*-} [options]"
      builtin echo "List available commands"
      builtin echo "Options:"
      builtin echo "  -h, --help  Show this help message"
      exit 0
      ;;
  esac
  find "${TEXENV_ROOT}/libexec" -maxdepth 1 -type f -name "texenv-*" |
    awk -F/ '{gsub("texenv-","");if($NF !~ /^-.*$/){print $NF}}' |
    grep -v "libs" |
    sort
}

cmdCommands "${@}"
