#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Set global TeX Live version
cmdGlobal() {
  declare VERSION
  declare SCRIPT_NAME
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
    *)
      VERSION="${1:-}"
      ;;
  esac
  [[ -d "${TEXENV_VERSIONS}/${VERSION}" ]] || {
    builtin echo "${SCRIPT_NAME%%-*}: version ${VERSION} is not installed" >&2
    exit 1
  }
  [[ -z "${VERSION}" ]] && {
    if [[ -d "${TEXENV_VERSIONS}" ]]; then
      [[ -f "${TEXENV_ROOT}/${TEX_GLOBAL_VERSION_FILE}" ]] && {
        VERSION="$(cat "${TEXENV_ROOT}/${TEX_GLOBAL_VERSION_FILE}")"
      }
      [[ -z "${VERSION}" ]] && {
        builtin echo "${SCRIPT_NAME%%-*}: no version set (use 'texenv global <version>')" >&2
        exit 1
      }
      builtin echo "${VERSION}"
      exit 0
    else
      builtin echo "${SCRIPT_NAME%%-*}: no version set (use 'texenv global <version>')" >&2
      exit 1
    fi
  }
  {
    builtin echo "${VERSION}" > "${TEXENV_ROOT}/${TEX_GLOBAL_VERSION_FILE}"
  } || {
    builtin echo "${SCRIPT_NAME%%-*}: failed to set global version" >&2
    exit 1
  }
}

cmdGlobal "${@}"
