#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Initialize texenv environment
cmdInit() {
  declare cmdHelp
  declare SCRIPT_NAME
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -)
      builtin echo "export PATH=\"${TEXENV_BIN}:\${PATH}\""
      builtin echo "export PATH=\"${TEXENV_SHIMS}:\${PATH}\""
      builtin echo "export TEXENV_SHELL=\"${SHELL##*/}\""
      builtin echo "texenv() {"
      builtin echo "  local CMD"
      builtin echo "  CMD=\"\${1:-}\""
      builtin echo "  [[ \"\${#}\" -gt 0 ]] && shift"
      builtin echo "  case \"\${CMD}\" in"
      builtin echo "    shell)"
      builtin echo "      eval \"\$(command texenv \"\${CMD}\" \"\${@}\")\";;"
      builtin echo "    *)"
      builtin echo "      command texenv \"\${CMD}\" \"\${@}\";;"
      builtin echo "  esac"
      builtin echo "}"
      builtin echo "texenv init > /dev/null 2>&1"
      exit 0
      ;;
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  {
    builtin echo "Initializing ${SCRIPT_NAME%%-*} environment..."
    [[ -d "${TEXENV_ROOT}" ]] || mkdir -p "${TEXENV_ROOT}"
    [[ -d "${TEXENV_VERSIONS}" ]] || mkdir -p "${TEXENV_VERSIONS}"
    [[ -d "${TEXENV_CONFIG}" ]] || mkdir -p "${TEXENV_CONFIG}"
    [[ -d "${TEXENV_SHIMS}" ]] || mkdir -p "${TEXENV_SHIMS}"
    [[ -d "${TEXMF_HOME}" ]] || mkdir -p "${TEXMF_HOME}"
    [[ -f "${TEXENV_ROOT}/${TEX_GLOBAL_VERSION_FILE}" ]] || touch "${TEXENV_ROOT}/${TEX_GLOBAL_VERSION_FILE}"
    builtin echo "${SCRIPT_NAME%%-*} initialized at ${TEXENV_ROOT}"
  } || {
    builtin echo "${SCRIPT_NAME%%-*}: failed to initialize" >&2
    exit 1
  }
}

cmdInit "${@}"
