#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Execute command in current TeX Live version
cmdExec() {
  declare cmdHelp
  declare libs
  declare runHooks
  declare executeRun
  declare SCRIPT_NAME
  declare SUBCMD_NAME
  SCRIPT_NAME="${0##*/}"
  SUBCMD_NAME="${SCRIPT_NAME##*-}"
  libs="$(builtin type -P "texenv-libs" || true)"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  runHooks="${libs} runHooks"
  executeRun="${libs} executeRun"
  [[ -z "${libs}" || -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SUBCMD_NAME}"
      ;;
  esac
  ${runHooks} "${SUBCMD_NAME}" pre "${@}"
  ${runHooks} "${SUBCMD_NAME}-${1:-}" pre "${@}"
  ${executeRun} "${@}"
  ${runHooks} "${SUBCMD_NAME}" post "${@}"
  ${runHooks} "${SUBCMD_NAME}-${1:-}" post "${@}"
}

cmdExec "${@}"
