#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Show current TeX Live version
cmdVersion() {
  declare VERSION
  declare VERSION_PATH
  declare -A TEX_VERSION_INFO
  declare SCRIPT_NAME
  declare libs
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  libs="$(builtin type -P "texenv-libs" || true)"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${libs}" || -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  if [[ -d "${TEXENV_VERSIONS}" ]]; then
    while IFS=': ' read -r KEY VALUE; do
      [[ -n "${KEY}" && -n "${VALUE}" ]] && TEX_VERSION_INFO["${KEY}"]="${VALUE}"
    done < <("${libs}" resolveVersion || true)
    VERSION="${TEX_VERSION_INFO["TinyTeX-Version"]:-}"
    VERSION_PATH="${TEX_VERSION_INFO["TinyTeX-Path"]:-}"
    [[ -z "${VERSION}" ]] && {
      builtin echo "${SCRIPT_NAME%%-*}: no version set (use '${SCRIPT_NAME%%-*} global <version>' or '${SCRIPT_NAME%%-*} local <version>')" >&2
      exit 1
    }
    builtin echo "${VERSION}$([[ -n "${VERSION_PATH}" ]] && builtin echo " (set by ${VERSION_PATH})")"
  else
    builtin echo "${SCRIPT_NAME%%-*}: no version set (use '${SCRIPT_NAME%%-*} global <version>' or '${SCRIPT_NAME%%-*} local <version>')" >&2
    exit 1
  fi
}

cmdVersion "${@}"
