#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

cmdShell() {
  declare INSTALLED_VERSIONS
  declare SCRIPT_NAME
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${cmdHelp}" ]] && {
    builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: required component(s) missing\""
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec echo "builtin echo '$("${cmdHelp}" "${SCRIPT_NAME##*-}")'"
      ;;
  esac
  if [[ -n "${1:-}" ]]; then
    [[ ! -d "${TEXENV_VERSIONS:-}" ]] && {
      builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: no versions installed\""
      exit 1
    }
    INSTALLED_VERSIONS="$(find "${TEXENV_VERSIONS}" -maxdepth 1 ! -name "${TEXENV_VERSIONS##*/}" -type d | awk -F/ '{print $NF}')"
    if ! grep -qxF "${1}" <<< "${INSTALLED_VERSIONS}" 2> /dev/null; then
      builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: version '${1}' is not installed\""
      exit 1
    else
      builtin echo "export TEXENV_VERSION=\"${1}\""
      builtin echo "builtin echo \"${1}\""
    fi
  elif [[ -n "${TEXENV_VERSION}" ]]; then
    builtin echo "builtin echo \"${TEXENV_VERSION}\""
  else
    builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: no shell-specific version configured\""
  fi
}

cmdShell "${@}"
