#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Show path to shim for specified command
cmdWhich() {
  declare CMD_NAME
  declare CMD_PATH
  declare SCRIPT_NAME
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  CMD_NAME="${1:-}"
  [[ -z "${CMD_NAME}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: no command specified" >&2
    exit 1
  }
  CMD_PATH="${TEXENV_SHIMS}/${CMD_NAME}"
  [[ -x "${CMD_PATH}" ]] || {
    builtin echo "${SCRIPT_NAME%%-*}: command '${CMD_NAME}' not found" >&2
    exit 1
  }
  builtin echo "${CMD_PATH}"
}

cmdWhich "${@}"
