#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

cmdShell() {
  declare INSTALLED_VERSIONS
  declare SCRIPT_NAME
  declare libs
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  libs="$(builtin type -P "texenv-libs" || true)"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${libs}" || -z "${cmdHelp}" ]] && {
    builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: required component(s) missing\""
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  if [[ -n "${1:-}" ]]; then
    "${libs}" isSafeVersion "${1}" || {
      builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: invalid version identifier\""
      exit 1
    }
    [[ ! -d "${TEXENV_VERSIONS:-}" ]] && {
      builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: no versions installed\""
      exit 1
    }
    INSTALLED_VERSIONS="$(find "${TEXENV_VERSIONS}" -maxdepth 1 ! -name "${TEXENV_VERSIONS##*/}" -type d | awk -F/ '{print $NF}')"
    if ! grep -qxF "${1}" <<< "${INSTALLED_VERSIONS}" 2> /dev/null; then
      builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: version '${1}' is not installed\""
      exit 1
    else
      builtin printf 'export TEXENV_VERSION=%s\n' "$("${libs}" shellQuote "${1}")"
      builtin printf 'builtin echo %s\n' "$("${libs}" shellQuote "${1}")"
    fi
  elif [[ -n "${TEXENV_VERSION}" ]]; then
    "${libs}" isSafeVersion "${TEXENV_VERSION}" || {
      builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: invalid version identifier\""
      exit 1
    }
    builtin printf 'builtin echo %s\n' "$("${libs}" shellQuote "${TEXENV_VERSION}")"
  else
    builtin echo "builtin echo \"${SCRIPT_NAME%%-*}: no shell-specific version configured\""
  fi
}

cmdShell "${@}"
