#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Manage tlmgr repository
cmdRepo() {
  declare libs
  declare cmdHelp
  declare -a executeRun
  declare -a resolveVersion
  declare VERSION
  declare REPO
  declare DEFAULT_REPO
  declare VERSION_YEAR
  declare CURRENT_REPO
  declare CURRENT_YEAR
  declare MIRROR
  declare MIRROR_REPO
  declare REMOVE_MIRROR
  declare RESET
  declare UNIQUE_REPO
  declare MIRROR_FILE
  declare SCRIPT_NAME
  declare -A TEX_VERSION_INFO
  declare regex
  SCRIPT_NAME="${0##*/}"
  libs="$(builtin type -P "texenv-libs" || true)"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  executeRun=("${libs}" executeRun)
  resolveVersion=("${libs}" resolveVersion)
  [[ -z "${libs}" || -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -s | --show)
      "${executeRun[@]}" tlmgr option repository | awk -F": " '{print $2}'
      exit 0
      ;;
    -m | --mirror)
      MIRROR=1
      shift || true
      MIRROR_REPO="${1:-}"
      ;;
    -r | --reset)
      RESET=1
      ;;
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  while IFS=': ' read -r KEY VALUE; do
    [[ -n "${KEY}" && -n "${VALUE}" ]] && TEX_VERSION_INFO["${KEY}"]="${VALUE}"
  done < <("${resolveVersion[@]}" || true)
  VERSION="${TEX_VERSION_INFO["TinyTeX-Version"]:-}"
  [[ -z "${VERSION}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: no version set (use '${SCRIPT_NAME%%-*} global <version>' or '${SCRIPT_NAME%%-*} local <version>')" >&2
    exit 1
  }
  "${libs}" isSafeVersion "${VERSION}" || {
    builtin echo "${SCRIPT_NAME%%-*}: invalid version identifier" >&2
    exit 1
  }
  regex='^(https?|ftp|file)://.*'
  DEFAULT_REPO="https://ctan.math.illinois.edu/systems/texlive/tlnet"
  MIRROR_FILE="${TEXENV_CONFIG}/${VERSION}/mirror_repo.txt"
  [[ -f "${MIRROR_FILE}" ]] && {
    UNIQUE_REPO="$(cat "${MIRROR_FILE}")"
    [[ -z "${UNIQUE_REPO}" ]] && {
      builtin echo "${SCRIPT_NAME%%-*}: no mirror repository specified" >&2
      exit 1
    }
  }
  CURRENT_REPO="$("${executeRun[@]}" tlmgr option repository | awk -F": " '{print $2}')"
  if [[ "${MIRROR:-}" == 1 ]]; then
    [[ -d "${TEXENV_CONFIG}" ]] || {
      builtin echo "${SCRIPT_NAME%%-*}: run '${SCRIPT_NAME%%-*} init' first" >&2
      exit 1
    }
    [[ -z "${MIRROR_REPO}" ]] && {
      builtin echo "${SCRIPT_NAME%%-*}: no mirror repository specified" >&2
      exit 1
    }
    [[ ! "${MIRROR_REPO}" =~ ${regex} ]] && {
      builtin echo "${SCRIPT_NAME%%-*}: invalid mirror repository URL '${MIRROR_REPO}'" >&2
      exit 1
    }
    [[ "${MIRROR_REPO}" == "${CURRENT_REPO}" ]] && {
      builtin echo "${SCRIPT_NAME%%-*}: Repository is already set to the specified mirror repository."
      return 0
    }
    REPO="${MIRROR_REPO}"
  elif [[ "${RESET:-}" == 1 ]]; then
    REPO="${DEFAULT_REPO}"
    REMOVE_MIRROR=1
    [[ "${REPO}" == "${CURRENT_REPO}" ]] && {
      [[ -f "${MIRROR_FILE}" ]] && rm -f "${MIRROR_FILE}"
      builtin echo "${SCRIPT_NAME%%-*}: Repository is already set to the default repository."
      return 0
    }
  elif [[ -n "${UNIQUE_REPO:-}" ]]; then
    [[ ! "${UNIQUE_REPO}" =~ ${regex} ]] && {
      builtin echo "${SCRIPT_NAME%%-*}: invalid mirror repository URL '${UNIQUE_REPO}'" >&2
      exit 1
    }
    [[ "${UNIQUE_REPO}" == "${CURRENT_REPO}" ]] && {
      builtin echo "${SCRIPT_NAME%%-*}: Repository is already set to the unique mirror repository."
      return 0
    }
    REPO="${UNIQUE_REPO}"
  else
    VERSION_YEAR="$("${executeRun[@]}" tlmgr --version | awk 'END{print $5}')"
    CURRENT_YEAR="$(date +%Y)"
    [[ -z "${VERSION_YEAR}" ]] && {
      builtin echo "${SCRIPT_NAME%%-*}: failed to determine TeX Live version year" >&2
      exit 1
    }
    if [[ "${VERSION_YEAR:-}" == "${CURRENT_YEAR}" ]]; then
      REPO="${DEFAULT_REPO}"
      [[ "${REPO}" == "${CURRENT_REPO}" ]] && {
        builtin echo "${SCRIPT_NAME%%-*}: Repository is already set to the latest TeX Live repository."
        return 0
      }
    else
      REPO="https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/${VERSION_YEAR}/tlnet-final"
      [[ "${REPO}" == "${CURRENT_REPO}" ]] && {
        builtin echo "${SCRIPT_NAME%%-*}: Repository is already set to the historic TeX Live repository."
        return 0
      }
    fi
  fi
  {
    builtin echo "${SCRIPT_NAME%%-*}: Setting tlmgr repository to ${REPO}..."
    [[ "${MIRROR:-}" == "1" ]] && {
      mkdir -p "${TEXENV_CONFIG}/${VERSION}"
    }
    if ! "${executeRun[@]}" tlmgr option repository "${REPO}"; then
      builtin echo "${SCRIPT_NAME%%-*}: failed to set tlmgr repository" >&2
      return 1
    fi
    if [[ "${MIRROR:-}" == "1" ]]; then
      builtin echo "${REPO}" > "${MIRROR_FILE}"
    elif [[ "${REMOVE_MIRROR:-}" == "1" ]]; then
      rm -f "${MIRROR_FILE}"
    fi
  } || {
    builtin echo "${SCRIPT_NAME%%-*}: failed to set tlmgr repository" >&2
    exit 1
  }
}

cmdRepo "${@}"
