#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Uninstall specified TeX Live version
cmdUninstall() {
  declare VERSION
  declare SCRIPT_NAME
  declare CONFIG_DIR
  declare cmdHelp
  declare cmdRehash
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  cmdRehash="$(builtin type -P 'texenv-rehash' || true)"
  [[ -z "${cmdHelp}" || -z "${cmdRehash}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
    *)
      VERSION="${1:-}"
      ;;
  esac
  [[ -d "${TEXENV_ROOT}" && -d "${TEXENV_VERSIONS}" && -d "${TEXENV_CONFIG}" && -d "${TEXENV_SHIMS}" ]] || {
    builtin echo "${SCRIPT_NAME%%-*}: run '${SCRIPT_NAME%%-*} init' first," >&2
    exit 1
  }
  [[ -z "${VERSION}" ]] && {
    builtin echo "USAGE: ${SCRIPT_NAME%%-*} uninstall <version>" >&2
    exit 1
  }
  [[ -d "${TEXENV_VERSIONS}/${VERSION}" ]] || {
    builtin echo "${SCRIPT_NAME%%-*}: version ${VERSION} is not installed" >&2
    exit 1
  }
  {
    builtin echo "Uninstalling version ${VERSION}..."
    rm -rf "${TEXENV_VERSIONS}/${VERSION:?}"
    CONFIG_DIR="${TEXENV_CONFIG}/${VERSION:?}"
    [[ -d "${CONFIG_DIR}" ]] && rm -rf "${CONFIG_DIR:?}"
    "${cmdRehash}" > /dev/null
    builtin echo "TeX Live version ${VERSION} uninstalled successfully."
  } || {
    builtin echo "${SCRIPT_NAME%%-*}: failed to uninstall version ${VERSION}" >&2
    exit 1
  }
}

cmdUninstall "${@}"
