#!/usr/bin/env bash

declare TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Show path to shim for specified command
cmdWhich() {
  declare CMD_NAME
  declare CMD_PATH
  declare SCRIPT_NAME
  SCRIPT_NAME="${0##*/}"
  case "${1:-}" in
    -h | --help)
      builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SCRIPT_NAME##*-} <cmd>"
      builtin echo "Show path to shim for specified command"
      builtin echo "Options:"
      builtin echo "  -h, --help  Show this help message"
      exit 0
      ;;
  esac
  CMD_NAME="${1:-}"
  [[ -z "${CMD_NAME}" ]] && {
    builtin echo "texenv: no command specified" >&2
    exit 1
  }
  CMD_PATH="${TEXENV_SHIMS}/${CMD_NAME}"
  [[ -x "${CMD_PATH}" ]] || {
    builtin echo "texenv: command '${CMD_NAME}' not found" >&2
    exit 1
  }
  builtin echo "${CMD_PATH}"
}

cmdWhich "${@}"
