#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Display texenv environment information
cmdEnv() {
  declare libs
  declare -a kpsewhich
  declare cmdHelp
  declare cmdRepo
  declare cmdVersion
  declare cmdVersions
  declare SCRIPT_NAME
  SCRIPT_NAME="${0##*/}"
  libs="$(builtin type -P "texenv-libs" || true)"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  cmdRepo="$(builtin type -P "texenv-repo" || true)"
  cmdVersion="$(builtin type -P "texenv-version" || true)"
  cmdVersions="$(builtin type -P "texenv-versions" || true)"
  kpsewhich=("${libs}" executeRun kpsewhich)
  [[ -z "${libs}" || -z "${cmdHelp}" || -z "${cmdRepo}" || -z "${cmdVersion}" || -z "${cmdVersions}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  runKpsewhich() {
    "${kpsewhich[@]}" "${@}"
  }
  cat << EOF
TinyTeX: $( ("${cmdVersion}" 2> /dev/null) || builtin echo "not set")
TEXMF PATHS:
  TEXHOME        = $(runKpsewhich -var-value=TEXMFHOME 2> /dev/null || builtin echo "${TEXMF_HOME}")
  TEXMFVAR       = $(runKpsewhich -var-value=TEXMFVAR 2> /dev/null || builtin echo "not set")
  TEXMFCONFIG    = $(runKpsewhich -var-value=TEXMFCONFIG 2> /dev/null || builtin echo "not set")
  TEXMFLOCAL     = $(runKpsewhich -var-value=TEXMFLOCAL 2> /dev/null || builtin echo "not set")
  TEXMFSYSVAR    = $(runKpsewhich -var-value=TEXMFSYSVAR 2> /dev/null || builtin echo "not set")
  TEXMFSYSCONFIG = $(runKpsewhich -var-value=TEXMFSYSCONFIG 2> /dev/null || builtin echo "not set")
  TEXMFDIST      = $(runKpsewhich -var-value=TEXMFDIST 2> /dev/null || builtin echo "not set")
Active repositories:
  $(
    REPO="$("${cmdRepo}" -s 2> /dev/null || true)"
    [[ -n "${REPO}" ]] && builtin echo "${REPO}" || builtin echo "not set"
  )
PATH (${SCRIPT_NAME%%-*}-related):
$(
    PATH_LIST="$(awk -F : '{for(i=1;i<=NF;i++) print $i}' <<< "${PATH}")"
    builtin echo "  bin:   ${TEXENV_BIN}$(grep -qxF "${TEXENV_BIN}" <<< "${PATH_LIST}" || builtin echo "   (not set in \$PATH)")"
    builtin echo "  shims: ${TEXENV_SHIMS}$(grep -qxF "${TEXENV_SHIMS}" <<< "${PATH_LIST}" || builtin echo " (not set in \$PATH)")"
  )
Installed versions:
$( ("${cmdVersions}" 2> /dev/null) || builtin echo "  not installed")
EOF
  exit 0
}

cmdEnv "${@}"
