#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

cmdRoot() {
  declare cmdHelp
  declare SCRIPT_NAME
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  [[ -z "${TEXENV_ROOT}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: TEXENV_ROOT is not set" >&2
    exit 1
  }
  builtin echo "${TEXENV_ROOT}"
}

cmdRoot "${@}"
