#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

cmdShims() {
  declare RESULT
  declare cmdHelp
  declare SCRIPT_NAME
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  RESULT="$(find "${TEXENV_SHIMS}" -maxdepth 1 -type l)"
  [[ -z "${RESULT}" ]] && {
    builtin echo "texenv: no shims generated" >&2
    exit 1
  }
  sort <<< "${RESULT}"
}

cmdShims "${@}"
