#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Execute command in current TeX Live version
cmdExec() {
  declare cmdHelp
  declare libs
  declare -a runHooks
  declare -a executeRun
  declare SCRIPT_NAME
  declare CMD_NAME
  declare SUBCMD_NAME
  SCRIPT_NAME="${0##*/}"
  CMD_NAME="${SCRIPT_NAME%%-*}"
  SUBCMD_NAME="${SCRIPT_NAME##*-}"
  libs="$(builtin type -P "${CMD_NAME}-libs" || true)"
  cmdHelp="$(builtin type -P "${CMD_NAME}-help" || true)"
  runHooks=("${libs}" runHooks)
  executeRun=("${libs}" executeRun)
  [[ -z "${libs}" || -z "${cmdHelp}" ]] && {
    builtin echo "${CMD_NAME}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SUBCMD_NAME}"
      ;;
  esac
  runHooksIfPresent() {
    declare EVENT
    declare PHASE
    EVENT="${1:-}"
    PHASE="${2:-}"
    shift 2 || true
    [[ -d "${TEXENV_HOOKS}/${EVENT}/${PHASE}" ]] || return 0
    "${runHooks[@]}" "${EVENT}" "${PHASE}" "${@}"
  }
  runHooksIfPresent "${SUBCMD_NAME}" pre "${@}"
  runHooksIfPresent "${SUBCMD_NAME}-${1:-}" pre "${@}"
  "${executeRun[@]}" "${@}"
  runHooksIfPresent "${SUBCMD_NAME}" post "${@}"
  runHooksIfPresent "${SUBCMD_NAME}-${1:-}" post "${@}"
}

cmdExec "${@}"
