#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Restore TeX packages from requirements file
cmdRestore() {
  declare FILE_NAME
  declare TEX_VERSION
  declare -A TEX_VERSION_INFO
  declare LOCK_TEX_VERSION
  declare LOCK_FLAG
  declare REQUIRE_LIST
  declare GREP_RC
  declare SCRIPT_NAME
  declare libs
  declare cmdHelp
  declare cmdExec
  SCRIPT_NAME="${0##*/}"
  libs="$(builtin type -P "texenv-libs" || true)"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  cmdExec="$(builtin type -P "texenv-exec" || true)"
  [[ -z "${libs}" || -z "${cmdHelp}" || -z "${cmdExec}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  if [[ -f "${TEX_REQUIREMENTS_LOCK_FILE}" ]]; then
    LOCK_FLAG=1
    FILE_NAME="${TEX_REQUIREMENTS_LOCK_FILE}"
  elif [[ -f "${TEX_REQUIREMENTS_FILE}" ]]; then
    FILE_NAME="${TEX_REQUIREMENTS_FILE}"
  else
    builtin echo "${SCRIPT_NAME%%-*}: no requirements file found" >&2
    exit 1
  fi
  while IFS=': ' read -r KEY VALUE; do
    [[ -n "${KEY}" && -n "${VALUE}" ]] && TEX_VERSION_INFO["${KEY}"]="${VALUE}"
  done < <("${libs}" resolveVersion || true)
  TEX_VERSION="${TEX_VERSION_INFO["TinyTeX-Version"]:-}"
  LOCK_TEX_VERSION="$(awk -F ": " 'NR==1{print $2}' "${FILE_NAME}")"
  [[ -n "${TEX_VERSION:-}" && -n "${LOCK_TEX_VERSION:-}" ]] && (("${TEX_VERSION%%.*}" < "${LOCK_TEX_VERSION%%.*}")) && {
    builtin echo "${SCRIPT_NAME%%-*}: TeX Live version ${TEX_VERSION%%.*} is older than the required version ${LOCK_TEX_VERSION%%.*}" >&2
    exit 1
  }
  {
    builtin echo "Restoring TeX packages from ${FILE_NAME}..."
    REQUIRE_LIST="$(grep -vxFf <("${cmdExec}" tlmgr info --only-installed --data name) <([[ -n "${LOCK_FLAG:-}" ]] && awk 'NR>1' < "${FILE_NAME}" || cat "${FILE_NAME}"))" || { GREP_RC=$?; [[ ${GREP_RC} -eq 1 ]] || return ${GREP_RC}; REQUIRE_LIST=""; }
    [[ -z "${REQUIRE_LIST}" ]] && {
      builtin echo "All required TeX packages are already installed."
      exit 0
    }
    "${cmdExec}" tlmgr install ${REQUIRE_LIST}
  } || {
    builtin echo "${SCRIPT_NAME%%-*}: failed to restore TeX packages" >&2
    exit 1
  }
}

cmdRestore ${@+"${@}"}
