#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Uninstall specified TeX Live version
cmdUninstall() {
  declare VERSION
  declare SCRIPT_NAME
  declare CMD_NAME
  declare SUBCMD_NAME
  declare CONFIG_DIR
  declare libs
  declare -a runHooks
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  CMD_NAME="${SCRIPT_NAME%%-*}"
  SUBCMD_NAME="${SCRIPT_NAME##*-}"
  libs="$(builtin type -P "${CMD_NAME}-libs" || true)"
  cmdHelp="$(builtin type -P "${CMD_NAME}-help" || true)"
  runHooks=("${libs}" runHooks)
  [[ -z "${libs}" || -z "${cmdHelp}" ]] && {
    builtin echo "${CMD_NAME}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SUBCMD_NAME}"
      ;;
    *)
      VERSION="${1:-}"
      ;;
  esac
  [[ -d "${TEXENV_ROOT}" && -d "${TEXENV_VERSIONS}" && -d "${TEXENV_CONFIG}" && -d "${TEXENV_SHIMS}" ]] || {
    builtin echo "${CMD_NAME}: run '${CMD_NAME} init' first," >&2
    exit 1
  }
  [[ -z "${VERSION}" ]] && {
    builtin echo "USAGE: ${CMD_NAME} ${SUBCMD_NAME} <version>" >&2
    exit 1
  }
  "${libs}" isSafeVersion "${VERSION}" || {
    builtin echo "${CMD_NAME}: invalid version identifier" >&2
    exit 1
  }
  [[ -d "${TEXENV_VERSIONS}/${VERSION}" ]] || {
    builtin echo "${CMD_NAME}: version ${VERSION} is not installed" >&2
    exit 1
  }
  {
    builtin echo "Uninstalling version ${VERSION}..."
    rm -rf "${TEXENV_VERSIONS}/${VERSION:?}"
    CONFIG_DIR="${TEXENV_CONFIG}/${VERSION:?}"
    [[ -d "${CONFIG_DIR}" ]] && rm -rf "${CONFIG_DIR:?}"
    "${runHooks[@]}" "${SUBCMD_NAME}" post "${@}"
    builtin echo "TeX Live version ${VERSION} uninstalled successfully."
  } || {
    builtin echo "${CMD_NAME}: failed to uninstall version ${VERSION}" >&2
    exit 1
  }
}

cmdUninstall "${@}"
