#!/usr/bin/env bash

declare TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Show current TeX Live version
cmdVersion() {
  declare VERSION
  declare VERSION_PATH
  declare TEX_VERSION_INFO
  declare SCRIPT_NAME
  declare libs
  SCRIPT_NAME="${0##*/}"
  libs="$(type -P "texenv-libs" || true)"
  [[ -z "${libs}" ]] && {
    builtin echo "texenv: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SCRIPT_NAME##*-} [options]"
      builtin echo "Show current TeX Live version"
      builtin echo "Options:"
      builtin echo "  -h, --help  Show this help message"
      exit 0
      ;;
  esac
  if [[ -d "${TEXENV_VERSIONS}" ]]; then
    TEX_VERSION_INFO="$("${libs}" resolveVersion || true)"
    VERSION="$(awk -F": " '/TinyTeX-Version: /{print $2}' <<< "${TEX_VERSION_INFO}")"
    VERSION_PATH="$(awk -F": " '/TinyTeX-Path: /{print $2}' <<< "${TEX_VERSION_INFO}")"
    [[ -z "${VERSION}" || -z "${VERSION_PATH}" ]] && {
      builtin echo "texenv: no version set (use 'texenv global <version>' or 'texenv local <version>')" >&2
      exit 1
    }
    builtin echo "${VERSION} (set by ${VERSION_PATH})"
  else
    builtin echo "texenv: no version set (use 'texenv global <version>' or 'texenv local <version>')" >&2
    exit 1
  fi
}

cmdVersion "${@}"
