#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Set local TeX Live version
cmdLocal() {
  declare DIR
  declare VERSION
  declare SCRIPT_NAME
  SCRIPT_NAME="${0##*/}"
  DIR="${TEXENV_DIR}"
  case "${1:-}" in
    -h | --help)
      builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SCRIPT_NAME##*-} [options] <version>"
      builtin echo "Set local TeX Live version"
      builtin echo "Options:"
      builtin echo "  -h, --help  Show this help message"
      exit 0
      ;;
    *)
      VERSION="${1:-}"
      ;;
  esac
  [[ -d "${TEXENV_VERSIONS}/${VERSION}" ]] || {
    builtin echo "texenv: version ${VERSION} is not installed" >&2
    exit 1
  }
  [[ -z "${VERSION}" ]] && {
    if [[ -d "${TEXENV_VERSIONS}" ]]; then
      [[ -f "${DIR}/${TEX_LOCAL_VERSION_FILE}" ]] && {
        VERSION="$(cat "${DIR}/${TEX_LOCAL_VERSION_FILE}")"
      }
      [[ -z "${VERSION}" ]] && {
        builtin echo "texenv: no version set (use 'texenv local <version>')" >&2
        exit 1
      }
      builtin echo "${VERSION}"
    else
      builtin echo "texenv: no version set (use 'texenv local <version>')" >&2
      exit 1
    fi
  }
  {
    builtin echo "${VERSION}" > "${PWD}/${TEX_LOCAL_VERSION_FILE}"
  } || {
    builtin echo "texenv: failed to set local version" >&2
    exit 1
  }
}

cmdLocal "${@}"
