#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Set local TeX Live version
cmdLocal() {
  declare DIR
  declare VERSION
  declare SCRIPT_NAME
  declare libs
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  DIR="${TEXENV_DIR}"
  libs="$(builtin type -P "texenv-libs" || true)"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${libs}" || -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
    *)
      VERSION="${1:-}"
      ;;
  esac
  [[ -z "${VERSION}" ]] && {
    if [[ -d "${TEXENV_VERSIONS}" ]]; then
      [[ -f "${DIR}/${TEX_LOCAL_VERSION_FILE}" ]] && {
        VERSION="$(cat "${DIR}/${TEX_LOCAL_VERSION_FILE}")"
      }
      [[ -z "${VERSION}" ]] && {
        builtin echo "${SCRIPT_NAME%%-*}: no version set (use '${SCRIPT_NAME%%-*} local <version>')" >&2
        exit 1
      }
      "${libs}" isSafeVersion "${VERSION}" || {
        builtin echo "${SCRIPT_NAME%%-*}: invalid version identifier" >&2
        exit 1
      }
      builtin echo "${VERSION}"
      exit 0
    else
      builtin echo "${SCRIPT_NAME%%-*}: no version set (use '${SCRIPT_NAME%%-*} local <version>')" >&2
      exit 1
    fi
  }
  "${libs}" isSafeVersion "${VERSION}" || {
    builtin echo "${SCRIPT_NAME%%-*}: invalid version identifier" >&2
    exit 1
  }
  [[ -d "${TEXENV_VERSIONS}/${VERSION}" ]] || {
    builtin echo "${SCRIPT_NAME%%-*}: version ${VERSION} is not installed" >&2
    exit 1
  }
  {
    builtin echo "${VERSION}" > "${DIR}/${TEX_LOCAL_VERSION_FILE}"
  } || {
    builtin echo "${SCRIPT_NAME%%-*}: failed to set local version" >&2
    exit 1
  }
}

cmdLocal "${@}"
