#!/usr/bin/env bash

declare TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Show path to command for specified command
cmdWhere() {
  declare CMD_NAME
  declare CMD_PATH
  declare VERSION
  declare TEX_VERSION_INFO
  declare SCRIPT_NAME
  declare libs
  SCRIPT_NAME="${0##*/}"
  libs="$(type -P "texenv-libs" || true)"
  [[ -z "${libs}" ]] && {
    builtin echo "texenv: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SCRIPT_NAME##*-} <cmd>"
      builtin echo "Show path to command in current TeX Live version"
      builtin echo "Options:"
      builtin echo "  -h, --help  Show this help message"
      exit 0
      ;;
  esac
  CMD_NAME="${1:-}"
  [[ -z "${CMD_NAME}" ]] && {
    builtin echo "texenv: no command specified" >&2
    exit 1
  }
  TEX_VERSION_INFO="$("${libs}" resolveVersion || true)"
  VERSION="$(awk -F": " '/TinyTeX-Version: /{print $2}' <<< "${TEX_VERSION_INFO}")"
  [[ -z "${VERSION}" ]] && {
    builtin echo "texenv: no version set (use 'texenv global <version>' or 'texenv local <version>')" >&2
    exit 1
  }
  CMD_PATH="${TEXENV_VERSIONS}/${VERSION}/bin/${TEXENV_PLATFORM}/${CMD_NAME}"
  [[ -x "${CMD_PATH}" ]] || {
    builtin echo "texenv: command '${CMD_NAME}' not found in version '${VERSION}'" >&2
    exit 1
  }
  builtin echo "${CMD_PATH}"
}

cmdWhere "${@}"
