#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Show path to command in all installed TeX Live versions
cmdWhence() {
  declare CMD_NAME
  declare RESULT
  declare SCRIPT_NAME
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  CMD_NAME="${1:-}"
  [[ -z "${CMD_NAME}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: no command specified" >&2
    exit 1
  }
  [[ ! -d "${TEXENV_VERSIONS}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: no versions installed" >&2
    exit 1
  }
  if [[ -f "${TEX_CMD_LIST_CACHE}" ]]; then
    RESULT="$(grep "/${CMD_NAME}$" "${TEX_CMD_LIST_CACHE}")"
  else
    RESULT="$(find "${TEXENV_VERSIONS}" -path "*/bin/${TEXENV_PLATFORM}/${CMD_NAME}" ! -type d -exec bash -c 'for f in "${@}"; do [[ -x "${f}" ]] && builtin echo "${f}"; done' _ {} +)"
  fi
  [[ -z "${RESULT}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: command '${CMD_NAME}' not found" >&2
    exit 1
  }
  awk -F/ '{print $(NF-3) " => " $0}' <<< "${RESULT}" |
    sort
}

cmdWhence "${@}"
