#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# List installed TeX Live versions
cmdVersions() {
  declare VERSION
  declare VERSION_PATH
  declare TEX_VERSION_INFO
  declare VERSIONS
  declare SCRIPT_NAME
  declare libs
  declare cmdHelp
  SCRIPT_NAME="${0##*/}"
  libs="$(builtin type -P "texenv-libs" || true)"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  [[ -z "${libs}" || -z "${cmdHelp}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  if [[ -d "${TEXENV_VERSIONS}" ]]; then
    TEX_VERSION_INFO="$("${libs}" resolveVersion || true)"
    VERSION="$(awk -F": " '/TinyTeX-Version: /{print $2}' <<< "${TEX_VERSION_INFO}")"
    VERSION_PATH="$(awk -F": " '/TinyTeX-Path: /{print $2}' <<< "${TEX_VERSION_INFO}")"
    VERSIONS="$(find "${TEXENV_VERSIONS}" -maxdepth 1 ! -name "${TEXENV_VERSIONS##*/}" -type d)"
    [[ -z "${VERSIONS}" ]] && {
      builtin echo "${SCRIPT_NAME%%-*}: no versions installed" >&2
      exit 1
    }
    sort <<< "${VERSIONS}" |
      awk -F/ -v ver="${VERSION}" -v ver_path="${VERSION_PATH}" '{
          if ($NF == ver) {
            printf("* %s (set by %s)\n", $NF, ver_path)
          } else {
            printf("  %s\n", $NF)
          }
        }'
  else
    builtin echo "${SCRIPT_NAME%%-*}: no versions installed" >&2
    exit 1
  fi
}

cmdVersions "${@}"
