#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Freeze TeX packages to requirements file
cmdFreeze() {
  declare FILE
  declare TEX_VERSION
  declare SCRIPT_NAME
  declare cmdHelp
  declare cmdExec
  declare cmdVersion
  SCRIPT_NAME="${0##*/}"
  cmdHelp="$(builtin type -P "texenv-help" || true)"
  cmdExec="$(builtin type -P "texenv-exec" || true)"
  cmdVersion="$(builtin type -P "texenv-version" || true)"
  [[ -z "${cmdHelp}" || -z "${cmdExec}" || -z "${cmdVersion}" ]] && {
    builtin echo "${SCRIPT_NAME%%-*}: required component(s) missing" >&2
    exit 1
  }
  "${cmdVersion}" > /dev/null
  FILE="${TEX_REQUIREMENTS_FILE}"
  case "${1:-}" in
    -l | --lock)
      FILE="${TEX_REQUIREMENTS_LOCK_FILE}"
      TEX_VERSION="$("${cmdExec}" tlmgr --version | awk 'END{print $5}')"
      ;;
    -h | --help)
      builtin exec "${cmdHelp}" "${SCRIPT_NAME##*-}"
      ;;
  esac
  {
    builtin echo "Freezing TeX packages to ${FILE}..."
    cat <([[ -z "${TEX_VERSION:-}" ]] || builtin echo "# TeX Live: ${TEX_VERSION}") <("${cmdExec}" tlmgr info --only-installed --data name) > "${FILE}"
  } || {
    builtin echo "${SCRIPT_NAME%%-*}: failed to freeze TeX packages" >&2
    exit 1
  }
}

cmdFreeze "${@}"
