#!/usr/bin/env bash

declare -r TEXENV_DEBUG
[[ "${TEXENV_DEBUG}" == 1 ]] && set -x
set -euo pipefail

# Display texenv environment information
cmdEnv() {
  declare libs
  declare kpsewhich
  declare cmdRepo
  declare cmdVersion
  declare cmdVersions
  declare SCRIPT_NAME
  SCRIPT_NAME="${0##*/}"
  libs="$(type -P "texenv-libs" || true)"
  kpsewhich="${libs} executeRun kpsewhich"
  cmdRepo="$(type -P "texenv-repo" || true)"
  cmdVersion="$(type -P "texenv-version" || true)"
  cmdVersions="$(type -P "texenv-versions" || true)"
  [[ -z "${libs}" || -z "${cmdRepo}" || -z "${cmdVersion}" || -z "${cmdVersions}" ]] && {
    builtin echo "texenv: required component(s) missing" >&2
    exit 1
  }
  case "${1:-}" in
    -h | --help)
      builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SCRIPT_NAME##*-} [options]"
      builtin echo "Display texenv environment information"
      builtin echo "Options:"
      builtin echo "  -h, --help  Show this help message"
      exit 0
      ;;
  esac
  cat << EOF
TinyTeX: $( ("${cmdVersion}" 2> /dev/null) || builtin echo "not set")
TEXMF PATHS:
  TEXHOME        = $( (${kpsewhich} -var-value=TEXMFHOME 2> /dev/null) || builtin echo "${TEXMF_HOME}")
  TEXMFVAR       = $( (${kpsewhich} -var-value=TEXMFVAR 2> /dev/null) || builtin echo "not set")
  TEXMFCONFIG    = $( (${kpsewhich} -var-value=TEXMFCONFIG 2> /dev/null) || builtin echo "not set")
  TEXMFLOCAL     = $( (${kpsewhich} -var-value=TEXMFLOCAL 2> /dev/null) || builtin echo "not set")
  TEXMFSYSVAR    = $( (${kpsewhich} -var-value=TEXMFSYSVAR 2> /dev/null) || builtin echo "not set")
  TEXMFSYSCONFIG = $( (${kpsewhich} -var-value=TEXMFSYSCONFIG 2> /dev/null) || builtin echo "not set")
  TEXMFDIST      = $( (${kpsewhich} -var-value=TEXMFDIST 2> /dev/null) || builtin echo "not set")
Active repositories:
  $(
    REPO="$("${cmdRepo}" -s 2> /dev/null || true)"
    [[ -n "${REPO}" ]] && builtin echo "${REPO}" || builtin echo "not set"
  )
PATH (${SCRIPT_NAME%%-*}-related):
$(
    PATH_LIST="$(awk -F : '{for(i=1;i<=NF;i++) print $i}' <<< "${PATH}")"
    builtin echo "  bin:   ${TEXENV_BIN}$(grep -qxF "${TEXENV_BIN}" <<< "${PATH_LIST}" || builtin echo "   (not set in \$PATH)")"
    builtin echo "  shims: ${TEXENV_SHIMS}$(grep -qxF "${TEXENV_SHIMS}" <<< "${PATH_LIST}" || builtin echo " (not set in \$PATH)")"
  )
Installed versions:
$( ("${cmdVersions}" 2> /dev/null) || builtin echo "  not installed")
EOF
  exit 0
}

cmdEnv "${@}"
